---
version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest'

dependencies:
  galaxy:
    collections:
    - nutanix.ncp
  python:
  - ansible # This will install latest ansible
  - setuptools
  - wheel
  system:
  - vim
  # helpful for troubleshooting/editing

options:
  package_manager_path: /usr/bin/microdnf
